modLoader="javafml" 
loaderVersion="[35,)" 
license="LGPL-3.0 License"
issueTrackerURL="https://github.com/Exrion/DeusMachina-Mod/issues" 

[[mods]] 
modId="exriondeusmachina" 
version="0.1" 
displayName="Deus Machina" 
displayURL="https://github.com/Exrion/DeusMachina-Mod" 
logoFile="logo.png" #optional
credits="Thanks to all the people who helped me with my doubts!" #optional
authors="Exrion" #optional
description='''
A playground for my first venture into modding Minecraft. This mod is aimed to be an alternative to central storage mods such as AE2 and RS with concepts drawn from real life networking. 
'''